spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/static/**
server.compression.enabled=true


game.chess.js.location=/static/js/Chess.js
game.chess.move.js.location=Move.js
state.cache.duration=PT10M